export const BALL_CLICK = 'BALL_CLICK';
export const BALL_CLOSE = 'BALL_CLOSE';
export const BALL_SET = 'BALL_SET';

export const BALLTYPE_CHANGE = 'BALLTYPE_CHANGE';
export const RUNTYPE_CHANGE = 'RUNTYPE_CHANGE';
export const RUNS_CHANGE = 'RUNS_CHANGE';
export const REQUEST_BALLS_PENDING = 'REQUEST_BALLS_PENDING';
export const REQUEST_BALLS_SUCCESS = 'REQUEST_BALLS_SUCCESS';
export const REQUEST_BALLS_FAILED = 'REQUEST_BALLS_FAILED';
export const MATCH_OPEN = 'MATCH_OPEN';
export const BACK_CLICK = 'BACK_CLICK';
export const CREATEMATCH_CLICK = 'CREATEMATCH_CLICK';
export const INSERTMATCH_PENDING = 'INSERTMATCH_PENDING';
export const INSERTMATCH_SUCCESS = 'INSERTMATCH_SUCCESS';
export const INSERTMATCH_FAILED = 'INSERTMATCH_FAILED';
